theme: jekyll-theme-hacker
show_downloads: "true"
title: MK404 - Printer Not Found
description: A full-featured simulator for AVR-based Prusa FFF printers; with the capability to easily support any AVR-based machine with modular components.
github:
  zip_url: https://github.com/vintagepc/MK404/releases
  tar_url: https://github.com/vintagepc/MK404/releases
